### ISSUE TITLE
Support for CDNJS pull request 

### ISSUE THREAD

**Issue by averter** [burnpanck/MathJax-siunitx#11]
As stated by @burnpanck [here](https://github.com/burnpanck/MathJax-third-party-extensions/issues/5) 
_I have also created a pull request at CDNJS to include it there. However, I was unable to tick all the marks in their checklist, particularly regarding the popularity of this extension. I'm afraid at this point it might not get accepted. In that case, I propose to rely on rawgit (as the examples currently do)._
Anyone who uses (or wants to use) this package can state here their support for this request in the hope of future acceptance.

**Comment by burnpanck** [comment]
This repo is unmaintained and likely incompatible with recent versions of MathJax. Checkout https://github.com/limefrogyank/siunitx-pcc instead.
