### ISSUE TITLE
Cannot load package locally via wordpress mathjax-latex plugin

### ISSUE THREAD

**Issue by averter** [burnpanck/MathJax-siunitx#12]
I have tried to use mathjax-siunitx via the wordpress mathjax-latex plugin, as described [here](https://github.com/org2blog/org2blog#mathjax). I 1) downloaded the package in the top-level directory of my server, and 2) tried calling the siunitx.js file using the following Custom MathJax location `/MathJax-siunitx/siunitx.js`. Does anyone has a clue as to why this doesn't work? And if so, are there any things that I might try? Thank you in advance.

Note: I have also downloaded another version of Mathjax and tested the plugin successfully (but without siunitx obviously), so I am certain that the wordpress plugin is able to load a local MathJax.js file. I find it strange that this version has no such file though.

**Comment by burnpanck** [comment]
This repo is unmaintained, and likely incompatible with recent versions of MathJax. Checkout https://github.com/limefrogyank/siunitx-pcc instead.
