### ISSUE TITLE
MathJax 3 status?

### ISSUE THREAD

**Issue by ickc** [burnpanck/MathJax-siunitx#13]
Hi, I can't seem to make this work in MathJax 3. Is it currently working and if so could someone put an example setup? If not, is supporting MathJax 3 planned?

Thanks.

**Comment by solarchemist** [comment]
https://github.com/limefrogyank/siunitx-pcc is a siunitx v3 implementation for MathJax v3.

**Comment by burnpanck** [comment]
@solarchemist: Would it make sense that I link to that from the top-level readme of this repo?

**Comment by solarchemist** [comment]
Sure, please do! I did not want to create a new issue myself in case the repo was really unmaintained but thought I could at least leave a pointer since the question was already asked - so I really appreciate you still trawling the queue :-)

**Comment by burnpanck** [comment]
The repo is unmaintained (since many years actually), but I am still active - just not with anything related to MathJax.
