### ISSUE TITLE
Is the software still maintained as it seems to be deprecated?

### ISSUE THREAD

**Issue by piiskop** [burnpanck/MathJax-siunitx#14]
Looking into the main source file, i don't see that it supports the command `qty`. There's the deprecated `si` everywhere, even `unit` is missing. i couldn't make the sample HTML file work neither as it complains about a redirect loop.

**Comment by solarchemist** [comment]
For siunitx v3 support in MathJax v3 I can recommend https://github.com/limefrogyank/siunitx-pcc.
