### ISSUE TITLE
Support for sisetup and DeclareSIUnit

### ISSUE THREAD

**Issue by pkra** [burnpanck/MathJax-siunitx#4]
Originally filed at https://github.com/mathjax/MathJax-third-party-extensions/issues/37.

Quote

"Just wondering if sisetup and DeclareSIUnit are supported.  Because I cannot figure out how to make them work.

Specifically in my case:

`#+latex_header: \DeclareSIUnit\Molar{\textsc{m}}`
`#+latex_header: \sisetup{per-mode=symbol}`
"

**Comment by burnpanck** [comment]
This repo is unmaintained and likely incompatible with recent versions of MathJax. Checkout https://github.com/limefrogyank/siunitx-pcc instead.
