### ISSUE TITLE
Extension’s loadComplete call doesn't match the official guideline

### ISSUE THREAD

**Issue by muzimuzhi** [burnpanck/MathJax-siunitx#6]
Currently the `loadComplete` call in packaged `siunix.js` is 
```javascript
MathJax.Ajax.loadComplete("[Contrib]/siunitx/siunitx.js")
```
The path the call loads, `"[Contrib]/siunitx/siunitx.js"`, is inconsistent with 
* the guidelines ([#using-third-party-extensions](https://github.com/mathjax/MathJax-third-party-extensions#using-third-party-extensions)) provided by official MathJax-third-party-extensions repo
* the related documentation ([#custom-extension-path-configuration](http://docs.mathjax.org/en/latest/options/ThirdParty.html#custom-extension-path-configuration)) provided by official MathJax Doc,
* and the practices popular third party extension [`mhchem`](https://github.com/mhchem/MathJax-mhchem) obey.

Following the docs and practices, the path `loadComplete` loads should be `"[siunitx]/siunitx.js"`.

**Comment by burnpanck** [comment]
That must have been a change post the migration out of the MathJax-third-party-extensions repo. I didn't have time to spend on this project since then. If you make a PR, I'll gladly accept it.

**Comment by burnpanck** [comment]
This repo is unmaintained and likely incompatible with recent versions of MathJax. Checkout https://github.com/limefrogyank/siunitx-pcc instead.
